### ISSUE TITLE
Light/Dark palette switching with mkdocs's palette toggle

### ISSUE THREAD

**Issue by tylernguyen** [landmaj/mkdocs-d2-plugin#17]
Hello,

Currently, d2 only switches the theme in accordance with system/browser preference.

Is there a way to sync the theme with mkdocs's current palette instead?

Minimal reproduction for test:

[9.5.25+insiders.4.53.11-d2-does-not-respect-mkdocs-palette-toggle.zip](https://github.com/user-attachments/files/15525664/9.5.25%2Binsiders.4.53.11-d2-does-not-respect-mkdocs-palette-toggle.zip)

P.S. Basic function works great! Thank you for your work on this plugin.

**Comment by landmaj** [comment]
There is no way to sync the theme between D2 diagrams and MkDocs right now. [It should be possible](https://squidfunk.github.io/mkdocs-material/reference/images/#light-and-dark-mode) but I doubt it's as easy as it looks like since I embed SVG directly, otherwise links would not work. I'll give it a try when I have some free time.
  
Sorry for the late reply, I was on vacation.

**Comment by landmaj** [comment]
I finally got to it and released a beta version with support for light/dark mode switching. You can try it out by installing [1.5.0b2](https://pypi.org/project/mkdocs-d2-plugin/1.5.0b2/) or visiting [the plugin documentation](https://landmaj.github.io/mkdocs-d2-plugin/).

I have to fix a bug causing diagrams to not be rendered when `dark_theme` is disabled globally but enabled locally, which is why there is only a beta release for now.

**Comment by landmaj** [comment]
1.5.0 is released.
